### ISSUE TITLE
Unable to start docker instance

### ISSUE THREAD

**Issue by ghettodev** [gcarq/cdpnotify#1]
When I create the container it crashes on start. Any thoughts?

Logs: [cdpnotifier.log](https://github.com/gcarq/cdpnotify/files/2086627/cdpnotifier.log)

Docker version 17.05.0-ce, build 89658be
Python 3.6.5
Ubuntu 16.04.4 LTS \n \l

**Comment by gcarq** [comment]
It assumes a geth instance at http://localhost:8545, it is the default in config.json
```
...
"hosted_node_url": "http://localhost:8545",
...
```
The easiest way would be to put a free infura.io url as `hosted_node_url`

**Comment by ghettodev** [comment]
Ahh, I spaced on recognising the port. infura worked.
